---
- name: Set up Ansible user
  hosts: all
  - name: Ensure participant user name is present
    user: ansible
      state: present
      createhome: yes
      comment: 'Ansible connection user created during eko-Konnect SciGaIA training'
      group: sudo
      groups: sudo
      password: $6$GWzhGQqIh4O$MF3VmVOCmc8FHBXUSoPOkp9ot2.UBjFCNqPuHxkMCcv8wS6ZYRzyNmghc5eYVq0uvZIYGzb.ixXIh9eKqiR2t0
      when: ansible_os_family=='Debian'
